package main.java.leetcode.algorithms.easy.problems_301_400;

/**
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 *
 * Example 1:
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 *
 * Example 2:
 * Input: s = "", t = "y"
 * Output: "y"
 *
 * Example 3:
 * Input: s = "a", t = "aa"
 * Output: "a"
 *
 * Example 4:
 * Input: s = "ae", t = "aea"
 * Output: "a"
 *
 * Constraints:
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lower-case English letters.
 */
public class FindTheDifference {

    public char findTheDifference(String s, String t) {
        char result = t.charAt(t.length()-1);

        /**
         * XOR works with primitive type Char as well
         */
        for(int i=0; i<s.length(); i++) {
            result ^= s.charAt(i);
            result ^= t.charAt(i);
        }

        return result;
    }
}
